spring:
  application:
    name: web3-backend
  datasource:
    url: jdbc:mysql://localhost:3306/db_web3
    username: user
    password: Lamnguyen1962@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384
      linger-ms: 5
      compression-type: snappy
      acks: 1
    consumer:
      group-id: wallet-notifier
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      max-poll-records: 500

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.kunfeng2002.be002: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

web3j:
  client-address: http://localhost:8545
  network-id: 1

telegram:
  bot:
    username: taiteasicale_bot
    token: 8493544022:AAEL-OiS659ZDo6z8I4OPSi6uOHzG1OK9PY

# API Configuration
api:
  thegraph:
    token: "eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTQ3NjY0ODAsImp0aSI6IjgwNGY4OWVjLTEyMDMtNDc3Mi05ZmE1LTlhZDE1NTEwZmQxYyIsImlhdCI6MTc1ODc2NjQ4MCwiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIwbmFiaTM3MDI1ZjdmNmZiYmEyZmYiLCJ2IjoyLCJha2kiOiIwOTg5YWZiNjExMWYzMzkyOTA3NDcwNjA3N2VjMTdmNTg3NTBhYzA4ZWJjZDNmYWExZjE1ODBjYTg4N2ZkYmVmIiwidWlkIjoiMG5hYmkzNzAyNWY3ZjZmYmJhMmZmIiwic3Vic3RyZWFtc19wbGFuX3RpZXIiOiJGUkVFIiwiY2ZnIjp7IlNVQlNUUkVBTVNfTUFYX1JFUVVFU1RTIjoiMiIsIlNVQlNUUkVBTVNfUEFSQUxMRUxfSk9CUyI6IjUiLCJTVUJTVFJFQU1TX1BBUkFMTEVMX1dPUktFUlMiOiI1In19.lzRoHd-qO6h8sG_-uCqYQsbd6_zBTjRQF6bWffqqt8MXa7Lxboa28W1QXiZHEO7oiswdcAyduda6zGCO_MWsNw"
    api-key: "server_59905865e0d2ae9beb83c090a1809b4c"
    base-url: "https://token-api.thegraph.com"
    pancakeswap-url: "https://api.thegraph.com/subgraphs/name/pancakeswap/exchange"

  coinmarketcap:
    api-key: "bc17cc89-9246-45a4-8ec1-07865cba8445"
    base-url: "https://pro-api.coinmarketcap.com/v1"

  bscscan:
    api-key: "X4KAZBFGFFM3CJ762QM3M5YF5F5ZMHMQEC"
    base-url: "https://api.bscscan.com/api"

  coingecko:
    api-key: "CG-oUHtDQkWkh3Q9sk157QEP5qK"
    base-url: "https://api.coingecko.com/api/v3"


network:
  # ethereum:
  #   rpc-url: wss://mainnet.infura.io/ws/v3/482a21b22a5f41c0b3c1ac57b19bf0a1
  #   chain-id: 1
  bsc:
#    rpc-url: wss://bnb-testnet.g.alchemy.com/v2/UN7-adHP_ym7EKduai7QA
#    chain-id: 97
      rpc-url: wss://bsc-mainnet.infura.io/ws/v3/482a21b22a5f41c0b3c1ac57b19bf0a1
      chain-id: 56
  # arbitrum:
  #   rpc-url: wss://arbitrum-mainnet.infura.io/ws/v3/482a21b22a5f41c0b3c1ac57b19bf0a1
  #   chain-id: 42161
  # optimism:
  #   rpc-url: wss://optimism-mainnet.infura.io/ws/v3/482a21b22a5f41c0b3c1ac57b19bf0a1
  #   chain-id: 10
  # avalanche:
  #   rpc-url: wss://avalanche-mainnet.infura.io/ws/v3/482a21b22a5f41c0b3c1ac57b19bf0a1
  #   chain-id: 43114

app:
  cache:
    refresh-interval: 300000
    fee-ttl: 15
  blockchain:
    reconnect-delay: 5000
    max-retry-attempts: 3
  crawler:
    batch-size: 100
    max-blocks-per-run: 1000
    enabled-networks: BSC
    crawl-interval: 30000
    enable-scheduled-crawling: true
    realtime:
      enabled: true
      interval: 30000
      max-blocks-per-crawl: 10
      auto-start: true