spring:
  application:
    name: web3-backend
  datasource:
    url: jdbc:mysql://localhost:3306/db_web3
    username: root
    password: taiteasicale
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384
      linger-ms: 5
      compression-type: snappy
      acks: 1
    consumer:
      group-id: wallet-notifier
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      max-poll-records: 500
    topics:
      coin-crawl: coin-crawl-topic
      coin-crawl-scheduled: coin-crawl-scheduled-topic

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

cors:
  allowed-origins: 
    - https://localhost:5173
    - https://8aa396bdad4a.ngrok-free.app
    - https://*.ngrok.io
    - https://*.ngrok-free.app
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.kunfeng2002.be002: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

web3j:
  client-address: http://localhost:8545
  network-id: 1

telegram:
  bot:
    username: telebotweb3bot
    token: 8396553381:AAEtH8Hwmd4XYfN3NiwPIrBQPzDYFdLfvW0

network:
  ethereum:
    rpc-url: wss://mainnet.infura.io/ws/v3/1552878eb6054c77b325b53266730979
    chain-id: 1
  bsc:
    rpc-url: wss://mantle-mainnet.infura.io/ws/v3/1552878eb6054c77b325b53266730979
    chain-id: 56
  arbitrum:
    rpc-url: wss://arbitrum-mainnet.infura.io/ws/v3/1552878eb6054c77b325b53266730979
    chain-id: 42161
  optimism:
    rpc-url: wss://optimism-mainnet.infura.io/ws/v3/1552878eb6054c77b325b53266730979
    chain-id: 10
  avalanche:
    rpc-url: wss://avalanche-mainnet.infura.io/ws/v3/1552878eb6054c77b325b53266730979
    chain-id: 43114

app:
  cache:
    refresh-interval: 300000
    fee-ttl: 15
  blockchain:
    reconnect-delay: 5000
    max-retry-attempts: 3

thegraph:
  token: eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTQ5NDIzMTcsImp0aSI6ImI4NTdkMTg4LTc3YjAtNDZiMC1hM2ExLTQyOTRjNGZiY2MzZiIsImlhdCI6MTc1ODk0MjMxNywiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIweG9uZTczMWUzZGY4NjRlZDZjMjIiLCJ2IjoyLCJha2kiOiI4MjdmZThmNTI0MzhlNGE4ZjVhODE4YjRjYjE2N2E1NzFjN2JkNTFkZTY3NGYxOTI5OTA4MDJiMjc3MWU5ZDg1IiwidWlkIjoiMHhvbmU3MzFlM2RmODY0ZWQ2YzIyIiwic3Vic3RyZWFtc19wbGFuX3RpZXIiOiJGUkVFIiwiY2ZnIjp7IlNVQlNUUkVBTVNfTUFYX1JFUVVFU1RTIjoiMiIsIlNVQlNUUkVBTVNfUEFSQUxMRUxfSk9CUyI6IjUiLCJTVUJTVFJFQU1TX1BBUkFMTEVMX1dPUktFUlMiOiI1In19.XVqDljf0KTVDBbCCciNagHB__acSGckx5tzYEhW1jDhO42XY_gNIGqtgMc8Medhjzht2gR41Bne-KHqRI9reLQ
  api-key: server_730ade174597d59a82ad91855aa0d9b6
  base-url: https://token-api.thegraph.com
  pancakeswap-url: https://api.thegraph.com/subgraphs/name/pancakeswap/exchange

coinmarketcap:
  api-key: bc17cc89-9246-45a4-8ec1-07865cba8445
  base-url: https://pro-api.coinmarketcap.com/v1

coingecko:
  api-key: CG-oUHtDQkWkh3Q9sk157QEP5qK
  base-url: https://api.coingecko.com/api/v3

bscscan:
  api-key: UB8S824RSBZAISNG7NSBHQM6791D6G1VS7
  base-url: https://api.bscscan.com/api

binance:
  api-key: y1onvQDl4ZHwlkbT0NfbuFwP16QUoDiq1zpnMubOJ99YAZoZQ9swyqzTasKtURj3
  secret-key: 43bkwRAQLAZR0hSRcLiZhnkKqym8L7q6lWMJaONC9JmbyIcai09QMsL3waPpbtf1
  base-url: https://api.binance.com/api/v3

etherscan:
  api-key: IJQDT6DF1XHRQ4ASCMFXJUQ9XQUA2QTSF5
  base-url: https://api.etherscan.io/api

moralis:
  api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjQ5ZTFiM2RjLTcxYjEtNDhhNi1hOThhLWUzZjY2ODMxZDBjYyIsIm9yZ0lkIjoiNDczMzQ1IiwidXNlcklkIjoiNDg2OTM0IiwidHlwZUlkIjoiZTI4NTFlMWQtY2JiYS00ZTlkLThjYjItZjIwNzRmM2JkODJkIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NTkzMDEzMTEsImV4cCI6NDkxNTA2MTMxMX0._GdmPwVE06BhV28iCDIFJ_kQyFlidzjhKLi9IZhY_bs
  base-url: https://deep-index.moralis.io/api/v2

debank:
  access-key: 85f91643d1717d421eaad5fb42134ff9138bee95
  base-url: https://pro-openapi.debank.com