spring:
  application:
    name: web3-backend
  datasource:
    url: jdbc:mysql://mysql:3306/db_web3  # dùng tên service mysql
    username: root
    password: 251202
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: kafka:9092  # dùng tên service kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384
      linger-ms: 5
      compression-type: snappy
      acks: 1
    consumer:
      group-id: wallet-notifier
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      max-poll-records: 500

  cache:
    type: redis

  data:
    redis:
      host: redis  # dùng tên service redis
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.kunfeng2002.be002: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

web3j:
  client-address: http://host.docker.internal:8545  # connect tới RPC chạy ở host
  network-id: 1

telegram:
  bot:
    username: taiteasicale_bot
    token: 8493544022:AAEL-OiS659ZDo6z8I4OPSi6uOHzG1OK9PY

network:
  ethereum:
    rpc-url: wss://sepolia.infura.io/ws/v3/97891bfdd6734fe3a7c6a748646aa2d4
    chain-id: 11155111
  bsc:
    rpc-url: wss://bnb-mainnet.g.alchemy.com/v2/wmnM3BSWRLGg__SqCyhEu
    chain-id: 56
  arbitrum:
    rpc-url: wss://arbitrum-sepolia.infura.io/ws/v3/97891bfdd6734fe3a7c6a748646aa2d4
    chain-id: 421614
  optimism:
    rpc-url: wss://optimism-sepolia.infura.io/ws/v3/97891bfdd6734fe3a7c6a748646aa2d4
    chain-id: 11155420
  avalanche:
    rpc-url: https://api.avax-test.network/ext/bc/C/rpc
    chain-id: 43113

app:
  cache:
    refresh-interval: 300000
  blockchain:
    reconnect-delay: 5000
    max-retry-attempts: 3