spring:
  application:
    name: web3-backend

  datasource:
    url: jdbc:mysql://localhost:3306/web3_db
    username: root
    password: taiteasicale
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384
      linger-ms: 5
      compression-type: snappy
      acks: 1
    consumer:
      group-id: wallet-notifier
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      max-poll-records: 500

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.kunfeng2002.be002: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG

web3j:
  client-address: http://host.docker.internal:8545
  network-id: 1

telegram:
  bot:
    username: taiteasicale_bot
    token: 8493544022:AAEL-OiS659ZDo6z8I4OPSi6uOHzG1OK9PY

network:
  ethereum:
    rpc-url: https://mainnet.infura.io/v3/87c5a6adc8704d5bb36a92fbb85f8f52
    chain-id: 1
  bsc:
    rpc-url: https://bsc-testnet.infura.io/v3/87c5a6adc8704d5bb36a92fbb85f8f52
    chain-id: 97
  arbitrum:
    rpc-url: wss://arbitrum-mainnet.infura.io/ws/v3/87c5a6adc8704d5bb36a92fbb85f8f52
    chain-id: 42161
  optimism:
    rpc-url: wss://optimism-mainnet.infura.io/ws/v3/87c5a6adc8704d5bb36a92fbb85f8f52
    chain-id: 10
  avalanche:
    rpc-url: wss://api.avax.network/ext/bc/C/ws
    chain-id: 43114

app:
  cache:
    refresh-interval: 300000
    fee-ttl: 15
  blockchain:
    reconnect-delay: 5000
    max-retry-attempts: 3
